### ISSUE TITLE
Better Coverage

### ISSUE THREAD

**Issue by jdan** [jdan/rubycards#12]
I integrated [coveralls](https://coveralls.io/) to our project. It allows us to see what lines are "covered" during testing, so we can better test the functionality of this gem.

So, my goal is to get this coverage to **90%**. I'll work on this for now, so I can better learn from @xtagon's original tests :+1:

**Comment by xtagon** [comment]
:+1:

**Comment by jdan** [comment]
Currently at **91%** :rocket:

https://coveralls.io/builds/103927

Just need a good spec for hands now
