### ISSUE TITLE
Refactor classes to module

### ISSUE THREAD

**Issue by jdan** [jdan/rubycards#3]
Continuing the discussion from #2, should we refactor the classes (Card, Deck, Hand) into a module?

I've pushed a commit to https://github.com/prezjordan/rubycards/tree/modulize. Some questions:
- Is the naming convention okay?
- Is it okay to have `VERSION` in this same module?
- Do I need `#encoding` at the top of each file?

**Comment by xtagon** [comment]
Naming convention is fine, as is having the `VERSION` in the same module. Looks good.

No idea about the `#encoding`question, sorry.

**Comment by jdan** [comment]
Thanks :) Tests are a-okay (adding `include RubyCards` is all it took). Merged.
