### ISSUE TITLE
Need for .rvmrc?

### ISSUE THREAD

**Issue by jdan** [jdan/rubycards#5]
Just curious what we need it for. I'm getting some errors trying to install p385 (which is another issue)

**EDIT:** .rvmrc, not RVM. oops

**Comment by xtagon** [comment]
No need for it in a gem. It's useful to put one in apps such as a Rails app, because in that case you want every developer working on the same exact version of Ruby or you can run into compatibility issues. In the case of a gem, you don't want to force a user or developer to a specific version.

**Comment by joeletizia** [comment]
True. Rip it out.
