### ISSUE TITLE
Better return values for Card, Deck, and Hand methods

### ISSUE THREAD

**Issue by jdan** [jdan/rubycards#6]
While just tinkering in irb, I get the following:

```
rubycards@master -> irb
irb(main):001:0> require 'rubycards'
=> true
irb(main):002:0> d = RubyCards::Deck.new
=> #<RubyCards::Deck:0x007f9eeb12c960 @cards=[╭───────╮
|   ♣   |
|       |
|   2   |
|   ♣   |

...

irb(main):003:0> 
```

It's not a bug per se... it's just a little annoying to see the card icons when declaring new Cards, Decks, and Hands. Try it in your terminal and you'll see why.

Instead, maybe these class methods should have better return values? I think `Card#to_s` is fine just the way it is.

**Comment by xtagon** [comment]
For cards, you could keep `#to_s` as is, and define `#inspect` to have a less obtrusive output such as `[♣2]`

For decks, I would just display the first and last few cards with `...` between.

**Comment by jdan** [comment]
Thanks @xtagon, works like a charm. :gem:
